# -*- coding: utf-8 -*-
"""Genre Detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsrAkg0l2xQv9Vt4Q9LoEOOawiO-RuQc
"""

!pip install youtube-transcript-api==0.6.3
from flask import Flask, request, jsonify
from youtube_transcript_api import YouTubeTranscriptApi,  TranscriptsDisabled
from transformers import BartTokenizer, BartForConditionalGeneration
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

tokenizer = BartTokenizer.from_pretrained('facebook/bart-large-cnn')
model = BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn')

def summarize_text(text):
      inputs = tokenizer.encode(text, return_tensors='pt', max_length=1024, truncation=True)
      summary_ids = model.generate(
          inputs,
          max_length=500,  # Adjust as needed
          min_length=100,  # Adjust as needed
          length_penalty=2.0,
          num_beams=4,
          early_stopping=True
      )
      summary_bart = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
      return summary_bart

def chunk_text(text, chunk_size=10):
    # Split text into words
    words = text.split()
    # Create chunks of chunk_size words each
    chunks = [' '.join(words[i:i + chunk_size]) for i in range(0, len(words), chunk_size)]
    return chunks

"""Input Text"""

# YouTube Video Link
url = "https://www.youtube.com/watch?v=u6lTKPTObEo" # Replace with your cooking video URL with subtitles

def summarizer(url):
  tokenizer = BartTokenizer.from_pretrained('facebook/bart-large-cnn')
  model = BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn')

def summarize_text(text):
  inputs = tokenizer.encode(text, return_tensors='pt', max_length=1024, truncation=True)
  summary_ids = model.generate(
     inputs,
          max_length=500,  # Adjust as needed
          min_length=100,  # Adjust as needed
          length_penalty=2.0,
          num_beams=4,
          early_stopping=True
      )
  summary_bart = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
  return summary_bart

def refine_summary_with_keywords(summary, keywords):
    # Convert keywords to a more natural format
  keywords_text = ", ".join(keywords)
  # Ensure the keywords are included by adding them to the summary
  refined_summary = f"{summary} \n\nKeywords: {keywords_text}"
  return refined_summary

def chunk_text(text, chunk_size=10):
  # Split text into words
  words = text.split()
  # Create chunks of chunk_size words each
  chunks = [' '.join(words[i:i + chunk_size]) for i in range(0, len(words), chunk_size)]
  return chunks

    # YouTube Video Link
link = url

  # Extract Unique ID
unique_id = link.split("=")[-1]

  # Get Transcript
transcript = YouTubeTranscriptApi.get_transcript(unique_id, languages=[
    'en-GB', 'en-US', 'en-CA', 'en-AU', 'en-IN', 'en-NZ', 'en-IE',
    'en-HK', 'en-SG', 'en-ZA', 'en', 'en-MY', 'en-PH', 'en-TT', 'en-JM',
    'en-BZ', 'en-KE', 'en-NG', 'en-ZM', 'en-BW', 'en-LK', 'en-MT',
    'en-UG', 'en-TZ', 'en-GH', 'en-PK', 'en-LK', 'en-RW', 'en-BD',
    'en-NA', 'en-ZW', 'en-OM', 'en-SD', 'en-MW', 'en-AE', 'en-LB',
    'en-JO', 'en-SA', 'en-EG', 'en-PS', 'en-KW', 'en-QA', 'en-BH',
    'en-IR', 'en-AF', 'en-LY', 'en-ET', 'en-SY', 'en-YE', 'en-MO',
    'en-IL', 'en-TR', 'en-UG', 'en-RW', 'en-BR', 'en-VN', 'en-MN',
    'en-KH', 'en-LA', 'en-MM', 'en-ID', 'en-FR', 'en-ES', 'en-IT',
    'en-NL', 'en-DE', 'en-SK', 'en-CZ', 'en-SE', 'en-FI', 'en-DK',
    'en-HU', 'en-PL', 'en-PT', 'en-RO', 'en-BG', 'en-GR', 'en-AL',
    'en-KR', 'en-JP', 'en-MY', 'en-TW', 'en-TH', 'en-MY', 'en-KR',
    'en-CO', 'en-VE', 'en-PE', 'en-EC', 'en-CL', 'en-AR', 'en-UY',
    'en-DO', 'en-PA', 'en-SV', 'en-HN', 'en-NI', 'en-GT', 'en-BR',
    'en-MX', 'en-CR', 'en-BY', 'en-KZ', 'en-UZ', 'en-AM', 'en-TR',
    'en-KG', 'en-MD', 'en-TJ', 'en-TM', 'en-AZ', 'en-MO', 'en-BH'
])

subtitle = " ".join([x['text'] for x in transcript])


  # Chunk the subtitle into pieces with a maximum of 200 words each
chunks = chunk_text(subtitle, chunk_size=200)

  # Summarize each chunk separately
summaries = [summarize_text(chunk) for chunk in chunks]

  # Combine the summaries into a single text block
full_summary = " ".join(summaries)

  # Compute TF-IDF scores for keywords
tf_idf_vectorizer = TfidfVectorizer(stop_words='english')
tf_idf_matrix = tf_idf_vectorizer.fit_transform(chunks)

  # Get feature names (words) and scores
feature_names = np.array(tf_idf_vectorizer.get_feature_names_out())
tf_idf_scores = np.asarray(tf_idf_matrix.mean(axis=0)).flatten()

  # Get top important words based on TF-IDF scores
num_top_words = 20  # Number of top words to include
top_word_indices = tf_idf_scores.argsort()[-num_top_words:][::-1]
top_words = feature_names[top_word_indices]

import pandas as pd

cooking_verbs = [
    "stir", "boil", "whisk", "bake", "sauté", "fry", "grill", "roast",
    "simmer", "steam", "blanch", "broil", "poach", "braise", "sear",
    "marinate", "knead", "fold", "chop", "slice", "dice", "mince",
    "peel", "mix", "blend", "caramelize", "barbecue", "stew", "toast",
    "scramble", "smear", "season", "garnish", "purée", "grate", "mash",
    "melt", "skim", "glaze", "deglaze", "temper", "crush", "steep",
    "beat", "preheat", "drizzle", "coat", "whip", "scald", "score",
    "parboil", "separate", "fillet", "clarify", "smoke", "reduce",
    "baste", "truss", "preserve", "pickle", "dry", "freeze", "ferment",
    "cure", "tenderize", "foam", "proof", "zest", "julienne", "shred",
    "core", "butter", "emulsify", "strain", "rinse", "dredge", "batter",
    "churn", "dissolve", "refrigerate", "hydrate", "infuse", "invert",
    "press", "render", "scorch", "shell", "shuck", "silk", "singe",
    "sliver", "snip", "soak", "sous-vide", "spatchcock", "sprinkle",
    "sweat", "toss", "trim", "turn", "vent", "bloom", "brown",
    "butterfly", "coddle", "cool", "cream", "devil", "flambé", "fold",
    "frost", "griddle", "marinate", "panfry", "parboil", "pinch",
    "poach", "pound", "reduce", "render", "rest", "roll", "sauté",
    "score", "scrape", "sift", "skin", "skim", "soak", "spread",
    "spritz", "steam", "strain", "thicken", "toss", "trim", "tuck",
    "unmold", "vacuum-pack", "warm", "weigh", "wet", "whip", "wipe",
    "yeast", "zest", "braise", "brine", "core", "cut", "dot",
    "frost", "marinate", "season", "shell", "simmer", "slice",
    "spoon", "top", "braise", "crimp", "flip", "grill", "pan-sear",
    "rotisserie", "spice", "temper", "wok", "pat", "fillet", "dice",
    "sift", "roll out", "fold in", "cube", "mold", "batch", "broth",
    "reduce", "infuse", "air-fry", "confit", "cure", "whisk in",
    "shake", "stir-fry", "cook off", "crust", "stabilize", "candy",
    "ferment", "dehydrate", "blitz", "quench", "snack", "dissolve",
    "spray", "lightly coat", "sauté", "lace", "encapsulate", "pierce",
    "steam roast", "flash fry", "glaze", "macaroon", "dip", "immolate",
    "fluff", "bind", "layer", "quick pickle", "spoon", "egg wash",
    "puree", "flatten", "conserve", "winnow", "julienne", "braise",
    "pan roast", "pinch off", "combine", "squeeze", "whittle",
    "splash", "scatter", "tap", "twist", "line", "nestle", "expose",
    "swirl", "kick", "aromatize", "simmer down", "cut in",
    "tenderize", "reduce heat", "wrap", "plating", "sear off",
    "carve", "aerate", "fold over", "roll up", "pour", "clamp",
    "splash", "float", "shimmer", "glint", "douse", "drain",
    "tamp", "cool down", "puff", "hull", "brew", "unroll",
    "slice thin", "pulp", "fume", "spray", "dry roast", "frost",
    "chill", "coat with", "in a hot pan", "crisp", "shatter",
    "break", "cut loose", "peel back", "pouch", "drizzle with",
    "adjust", "sauté on high", "pinch back", "fry up", "slosh",
    "bake blind", "bake to golden", "brush with", "roast off",
    "slice thick", "fill", "mix gently", "extract", "warm through",
    "fry until tender", "chill for freshness", "quick roast",
    "whip cream until stiff", "reduce to a glaze", "wrap tightly",
    "layer with cheese", "bake until set", "add cream",
    "broil until browned", "cook to al dente", "crisp the edges",
    "make a roux", "flavor with garlic", "toast nuts",
    "create a reduction", "add a dash", "grill to perfection",
    "let rest", "stir until thickened", "simmer with herbs",
    "heat gently", "cool completely", "infuse overnight",
    "pickle vegetables", "layer in a jar", "reduce by half",
    "garnish with microgreens", "serve in a ramekin",
    "plate with sauce", "top with herbs", "present in a tower",
    "swirl sauce on plate", "serve with a side salad",
    "arrange artfully", "serve in a martini glass", "layer with fruit",
    "freeze in ice cube trays", "store in freezer bags",
    "cool and portion", "vacuum seal for freshness",
    "defrost before use", "chill thoroughly", "keep refrigerated",
    "fold in chocolate", "shake and serve",
    "toss with vinaigrette", "whisk until combined",
    "mix into batter", "pour over", "sift over the top",
    "blanch and shock", "deglaze with wine", "smoke using chips",
    "sear with a blowtorch", "develop flavors over time",
    "confit garlic", "pickle with spices", "serve in a dome",
    "create a crust", "pat down evenly", "drizzle with oil",
    "smoke for depth", "chop finely", "slice diagonally",
    "whittle down", "scald milk", "coat in breadcrumbs",
    "serve in a bowl", "finish with a sprinkle of salt",
    "top with a cherry", "drizzle with balsamic reduction",
    "create height with layers", "serve warm",
    "serve chilled", "decorate with chocolate shavings",
    "slice for serving", "arrange in a spiral",
    "cut into triangles", "combine for stuffing",
    "whisk until frothy", "pinch edges", "wrap in bacon",
    "serve with a garnish", "infuse with citrus",
    "pair with fresh herbs", "build a salad",
    "dollop with yogurt", "elevate with acidity",
    "bring flavors together", "layer with sauces",
]

cooking_nouns = {


      "sugar", "salt", "flour", "butter", "olive oil", "vegetable oil", "sesame oil",
      "sunflower oil", "coconut oil", "ghee", "cream", "milk", "buttermilk", "yogurt",
      "cheese", "cream cheese", "paneer", "ricotta", "mozzarella", "feta", "goat cheese",
      "parmesan", "chocolate", "dark chocolate", "white chocolate", "cocoa powder",
      "honey", "maple syrup", "agave syrup", "corn syrup", "vanilla extract", "almond extract",
      "rose syrup", "saffron", "cardamom", "cloves", "cinnamon", "nutmeg", "allspice",
      "turmeric", "paprika", "cayenne pepper", "chili powder", "black pepper", "white pepper",
      "ginger", "garlic", "onion", "shallots", "leeks", "spring onions", "scallions",
      "tomatoes", "bell peppers", "green peppers", "red peppers", "chili peppers", "jalapenos",
      "cucumbers", "carrots", "potatoes", "sweet potatoes", "pumpkin", "squash", "zucchini",
      "broccoli", "cauliflower", "spinach", "kale", "lettuce", "arugula", "cabbage", "beets",
      "peas", "green beans", "asparagus", "eggplant", "avocado", "mushrooms", "artichokes",
      "corn", "cornstarch", "rice", "white rice", "brown rice", "basmati rice", "jasmine rice",
      "quinoa", "barley", "bulgur wheat", "oats", "pasta", "spaghetti", "penne", "macaroni",
      "noodles", "lasagna", "bread", "buns", "baguette", "tortillas", "pita", "naan", "croissants",
      "baking soda", "baking powder", "yeast", "cornmeal", "breadcrumbs", "almond flour", "coconut flour",
      "chickpea flour", "rice flour", "semolina", "polenta", "potato flour", "tapioca flour",
      "sesame seeds", "sunflower seeds", "pumpkin seeds", "chia seeds", "flaxseeds", "poppy seeds",
      "walnuts", "almonds", "pecans", "cashews", "hazelnuts", "pistachios", "macadamia nuts",
      "pine nuts", "peanuts", "nutmeg", "coconut", "dried fruit", "raisins", "dates", "figs",
      "prunes", "cranberries", "apples", "oranges", "bananas", "mango", "pineapple", "grapes",
      "pomegranate", "strawberries", "blueberries", "raspberries", "blackberries", "kiwi", "peaches",
      "plums", "cherries", "apricots", "pear", "melon", "watermelon", "papaya", "lychee", "guava",
      "lemon", "lime", "orange juice", "apple cider vinegar", "balsamic vinegar", "white vinegar",
      "rice vinegar", "red wine vinegar", "malt vinegar", "worcestershire sauce", "soy sauce",
      "teriyaki sauce", "hoisin sauce", "barbecue sauce", "hot sauce", "mustard", "ketchup",
      "mayonnaise", "sour cream", "tahini", "peanut butter", "almond butter", "chocolate spread",
      "jam", "jelly", "preserves", "pickles", "canned tomatoes", "tomato paste", "tomato sauce",
      "coconut milk", "coconut cream", "cream cheese", "cream of mushroom", "beef broth", "chicken broth",
      "vegetable broth", "stock", "coconut water", "coconut flakes", "powdered sugar", "brown sugar",
      "stevia", "agave nectar", "maple syrup", "cocoa butter", "marshmallows", "icing sugar",
      "syrup", "corn syrup", "chocolate chips", "toffee", "caramel", "shortening", "cornstarch",
      "gelatin", "pectin", "gellan gum", "xanthan gum", "gluten", "pasta sauce", "canned beans",
      "lentils", "chickpeas", "black beans", "kidney beans", "white beans", "green lentils",
      "red lentils", "mung beans", "soybeans", "tempeh", "tofu", "seitan", "quinoa", "spelt",
      "bulgur wheat", "farro", "buckwheat", "freekeh", "couscous", "pita bread", "tortillas",
      "naan", "dough", "fondant", "marzipan", "biscoff", "tapioca pearls", "pudding", "custard",
      "sorbet", "ice cream", "whipped cream", "gelato", "frozen yogurt", "curd", "besan",
      'chili', 'mango', 'curd', 'buttermilk', 'spices', 'sesame', 'butter', 'seeds', 'ginger', 'turmeric', 'cumin', 'sesame oil', 'fennel', 'coriander', 'garlic',
      # Fruits
      "Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry",
      "Blueberry", "Cherry", "Watermelon", "Kiwi", "Papaya", "Pomegranate",
      "Avocado", "Raspberry", "Blackberry", "Peach", "Plum", "Apricot",
      "Coconut", "Fig", "Lychee", "Tangerine", "Persimmon", "Dragon Fruit",
      "Passion Fruit", "Gooseberry", "Cranberry", "Starfruit", "Mulberry",
      "Durian", "Nectarine", "Kumquat", "Clementine", "Rambutan", "Soursop",
      "Plantain", "Jackfruit", "Custard Apple", "Quince", "Jujube",

      # Vegetables
      "Carrot", "Potato", "Tomato", "Cucumber", "Onion", "Garlic", "Lettuce",
      "Spinach", "Broccoli", "Cauliflower", "Bell Pepper", "Zucchini",
      "Eggplant", "Beet", "Radish", "Turnip", "Cabbage", "Kale", "Asparagus",
      "Brussels Sprout", "Green Bean", "Peas", "Celery", "Fennel", "Leek",
      "Mushroom", "Artichoke", "Squash", "Pumpkin", "Chard", "Parsnip",
      "Chives", "Scallion", "Jalapeño", "Cilantro", "Bok Choy", "Endive",
      "Arugula", "Radicchio", "Watercress", "Seaweed", "Kohlrabi", "Fenugreek",

      # Pasta & Noodles
      "Pasta", "Rice", "Noodles", "Spaghetti", "Fettuccine", "Penne",
      "Spaghetti", "Fettuccine", "Penne", "Macaroni", "Linguine", "Ravioli",
      "Fusilli", "Orzo", "Shells", "Lasagna", "Tagliatelle", "Ziti",
      "Capellini", "Pappardelle", "Bucatini", "Cavatappi", "Gemelli",
      "Vermicelli", "Gnocchi", "Manicotti", "Pici",

      # Dairy
      "Milk", "Cheese", "Yogurt", "Butter", "Cream", "Sour Cream",
      "Cottage Cheese", "Ricotta", "Goat Cheese", "Mozzarella",
      "Parmesan", "Feta", "Gouda", "Cheddar", "Brie", "Camembert",
      "Provolone", "Gruyere", "Mascarpone", "Heavy Cream", "Ice Cream", "Coffee",

      # Grains
      "Wheat", "Barley", "Rye", "Bulgur", "Semolina", "Spelt",
      "Triticale", "Oats", "Bread", "Couscous", "Seitan", "Quinoa", "Corn",
      "Buckwheat", "Amaranth", "Sorghum", "Millet", "Teff", "Chickpea Flour",
      "Almond Flour", "Coconut Flour", "Tapioca Flour", "Rice Flour",

      # Eggs & Meats
      "Eggs", "Bacon", "Sausage", "Ham", "Salami", "Chorizo",
      "Chicken", "Beef", "Pork", "Lamb", "Turkey", "Duck",
      "Goose", "Venison", "Pastrami", "Steak", "Filet Mignon", "Ground Beef",
      "Roast", "Meatballs", "Ribs", "Tenderloin", "Brisket",

      # Fish & Seafood
      "Salmon", "Tuna", "Cod", "Trout", "Sardines", "Shrimp", "Prawns",
      "Lobster", "Crab", "Mussels", "Clams", "Oysters", "Squid", "Octopus",

      # Oils & Vinegars
      "Olive Oil", "Vegetable Oil", "Coconut Oil", "Butter", "Ghee", "Sesame Oil",
      "Canola Oil", "Sunflower Oil", "Vinegar", "Balsamic Vinegar", "Apple Cider Vinegar",
      "Red Wine Vinegar", "White Wine Vinegar", "Rice Vinegar", "Malt Vinegar", "Sherry Vinegar",

      # Herbs & Spices
      "Salt", "Pepper", "Turmeric", "Ginger", "Cinnamon", "Nutmeg", "Cumin", "Coriander", "Cardamom",
      "Chili Powder", "Paprika", "Oregano", "Basil", "Thyme", "Rosemary", "Sage", "Bay Leaves",
      "Tarragon", "Parsley", "Chives", "Dill", "Fennel", "Cilantro", "Marjoram", "Garlic Powder",
      "Onion Powder", "Mustard", "Allspice", "Cloves", "Anise", "Saffron", "Mace", "Celery Salt", "cilly flakes"

      # Sauces & Condiments
      "Ketchup", "Mustard", "Mayonnaise", "Barbecue Sauce", "Soy Sauce", "Hot Sauce",
      "Worcestershire Sauce", "Vinegar", "Sriracha", "Tartar Sauce", "Chutney", "Relish",
      "Salad Dressing", "Teriyaki Sauce", "Tahini", "Pesto", "Piri Piri Sauce",

      # Baked Goods & Snacks
      "Bread", "Bagels", "Croissants", "Muffins", "Biscuits", "Cakes", "Cookies", "Pastries",
      "Chips", "Crackers", "Popcorn", "Pretzels", "Granola", "Cereal", "Rice Cakes",

      # Sweeteners & Other Ingredients
      "Sugar", "Brown Sugar", "Honey", "Maple Syrup", "Agave Syrup", "Molasses",
      "Stevia", "Sweetener", "Vanilla Extract", "Cocoa Powder", "Chocolate Chips",
      "Marshmallows", "Caramel", "Molasses", "Corn Syrup", "Cornstarch", "Baking Powder", "Baking Soda",
      "Gelatin", "Pectin", "Xanthan Gum", "Agar-Agar", "Arrowroot", "Vanilla Bean", "Peanut Butter",

      # Beverages
      "Water", "Juice", "Lemonade", "Tea", "Coffee", "Milk", "Hot Chocolate", "Smoothies",
      "Wine", "Beer", "Whiskey", "Vodka", "Gin", "Rum", "Tequila", "Brandy", "Cider",

      # Other Miscellaneous Cooking Items
      "Ice", "Tofu", "Tempeh", "Yogurt", "Nutritional Yeast", "Pita Bread", "Tortillas", "Naan",
      "Pita Chips", "Bulgur", "Polenta", "Fried Chicken", "Spring Rolls", "Dumplings", "Bao",
      "Tacos", "Quesadillas", "Burritos", "Empanadas", "Pizza", "Pasta Sauce", "Marinara Sauce",
      "Tomato Sauce", "Pesto", "Salsa", "Guacamole", "Hummus", "Dips", "Pudding", "Jelly", "Jam",

      "Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry",
      "Blueberry", "Cherry", "Watermelon", "Kiwi", "Papaya", "Pomegranate",
      "Avocado", "Raspberry", "Blackberry", "Peach", "Plum", "Apricot",
      "Coconut", "Fig", "Lychee", "Tangerine", "Persimmon", "Dragon Fruit",
      "Passion Fruit", "Gooseberry", "Cranberry", "Starfruit", "Mulberry",
      "Durian", "Nectarine", "Kumquat", "Clementine", "Rambutan", "Soursop",
      "Plantain", "Jackfruit", "Custard Apple", "Quince", "Jujube",

      # Vegetables
      "Carrot", "Potato", "Tomato", "Cucumber", "Onion", "Garlic", "Lettuce",
      "Spinach", "Broccoli", "Cauliflower", "Bell Pepper", "Zucchini",
      "Eggplant", "Beet", "Radish", "Turnip", "Cabbage", "Kale", "Asparagus",
      "Brussels Sprout", "Green Bean", "Peas", "Celery", "Fennel", "Leek",
      "Mushroom", "Artichoke", "Squash", "Pumpkin", "Chard", "Parsnip",
      "Chives", "Scallion", "Jalapeño", "Cilantro", "Bok Choy", "Endive",
      "Arugula", "Radicchio", "Watercress", "Seaweed", "Kohlrabi", "Fenugreek",

      # Pasta & Noodles
      "Pasta", "Rice", "Noodles", "Spaghetti", "Fettuccine", "Penne",
      "Spaghetti", "Fettuccine", "Penne", "Macaroni", "Linguine", "Ravioli",
      "Fusilli", "Orzo", "Shells", "Lasagna", "Tagliatelle", "Ziti",
      "Capellini", "Pappardelle", "Bucatini", "Cavatappi", "Gemelli",
      "Vermicelli", "Gnocchi", "Manicotti", "Pici",

      # Dairy
      "Milk", "Cheese", "Yogurt", "Butter", "Cream", "Sour Cream",
      "Cottage Cheese", "Ricotta", "Goat Cheese", "Mozzarella",
      "Parmesan", "Feta", "Gouda", "Cheddar", "Brie", "Camembert",
      "Provolone", "Gruyere", "Mascarpone", "Heavy Cream", "Ice Cream", "Coffee",

      # Grains
      "Wheat", "Barley", "Rye", "Bulgur", "Semolina", "Spelt",
      "Triticale", "Oats", "Bread", "Couscous", "Seitan", "Quinoa", "Corn",
      "Buckwheat", "Amaranth", "Sorghum", "Millet", "Teff", "Chickpea Flour",
      "Almond Flour", "Coconut Flour", "Tapioca Flour", "Rice Flour",

      # Eggs & Meats
      "Eggs", "Bacon", "Sausage", "Ham", "Salami", "Chorizo",
      "Chicken", "Beef", "Pork", "Lamb", "Turkey", "Duck",
      "Goose", "Venison", "Pastrami", "Steak", "Filet Mignon", "Ground Beef",
      "Roast", "Meatballs", "Ribs", "Tenderloin", "Brisket",

      # Fish & Seafood
      "Salmon", "Tuna", "Cod", "Trout", "Sardines", "Shrimp", "Prawns",
      "Lobster", "Crab", "Mussels", "Clams", "Oysters", "Squid", "Octopus",

      # Oils & Vinegars
      "Olive Oil", "Vegetable Oil", "Coconut Oil", "Butter", "Ghee", "Sesame Oil",
      "Canola Oil", "Sunflower Oil", "Vinegar", "Balsamic Vinegar", "Apple Cider Vinegar",
      "Red Wine Vinegar", "White Wine Vinegar", "Rice Vinegar", "Malt Vinegar", "Sherry Vinegar",

      # Herbs & Spices
      "Salt", "Pepper", "Turmeric", "Ginger", "Cinnamon", "Nutmeg", "Cumin", "Coriander", "Cardamom",
      "Chili Powder", "Paprika", "Oregano", "Basil", "Thyme", "Rosemary", "Sage", "Bay Leaves",
      "Tarragon", "Parsley", "Chives", "Dill", "Fennel", "Cilantro", "Marjoram", "Garlic Powder",
      "Onion Powder", "Mustard", "Allspice", "Cloves", "Anise", "Saffron", "Mace", "Celery Salt", "Cilly flakes",

      # Sauces & Condiments
      "Ketchup", "Mustard", "Mayonnaise", "Barbecue Sauce", "Soy Sauce", "Hot Sauce",
      "Worcestershire Sauce", "Vinegar", "Sriracha", "Tartar Sauce", "Chutney", "Relish",
      "Salad Dressing", "Teriyaki Sauce", "Tahini", "Pesto", "Piri Piri Sauce",

      # Baked Goods & Snacks
      "Bread", "Bagels", "Croissants", "Muffins", "Biscuits", "Cakes", "Cookies", "Pastries",
      "Chips", "Crackers", "Popcorn", "Pretzels", "Granola", "Cereal", "Rice Cakes",

      # Sweeteners & Other Ingredients
      "Sugar", "Brown Sugar", "Honey", "Maple Syrup", "Agave Syrup", "Molasses",
      "Stevia", "Sweetener", "Vanilla Extract", "Cocoa Powder", "Chocolate Chips",
      "Marshmallows", "Caramel", "Molasses", "Corn Syrup", "Cornstarch", "Baking Powder", "Baking Soda",
      "Gelatin", "Pectin", "Xanthan Gum", "Agar-Agar", "Arrowroot", "Vanilla Bean", "Peanut Butter",

      # Beverages
      "Water", "Juice", "Lemonade", "Tea", "Coffee", "Milk", "Hot Chocolate", "Smoothies",
      "Wine", "Beer", "Whiskey", "Vodka", "Gin", "Rum", "Tequila", "Brandy", "Cider",

      # Other Miscellaneous Cooking Items
      "Ice", "Tofu", "Tempeh", "Yogurt", "Nutritional Yeast", "Pita Bread", "Tortillas", "Naan",
      "Pita Chips", "Bulgur", "Polenta", "Fried Chicken", "Spring Rolls", "Dumplings", "Bao",
      "Tacos", "Quesadillas", "Burritos", "Empanadas", "Pizza", "Pasta Sauce", "Marinara Sauce",
      "Tomato Sauce", "Pesto", "Salsa", "Guacamole", "Hummus", "Dips", "Pudding", "Jelly", "Jam",

      # Indian Dishes
      "Biryani", "Butter Chicken", "Chicken Tikka Masala", "Palak Paneer", "Aloo Gobi", "Chole Bhature",
      "Pani Puri", "Samosa", "Dosa", "Idli", "Vada", "Pav Bhaji", "Rogan Josh", "Korma", "Dal Makhani",
      "Methi Thepla", "Tandoori Chicken", "Lassi", "Naan", "Paratha", "Aloo Paratha", "Bhindi Masala",
      "Mutter Paneer", "Tandoori Roti", "Gulab Jamun", "Jalebi", "Kachori", "Pakora", "Kadhi Pakora", "Pulao",
      "Khichdi", "Mysore Pak", "Gajar Halwa", "Lassi", "Rava Upma", "Chana Masala", "Pesarattu", "Rava Kesari",
      "Mohanthal", "Baingan Bharta", "Baati", "Gobi Manchurian", "Shahi Paneer", "Kadhi", "Aloo Tikki", "Dhokla",
      "Fried Papad", "Kebabs", "Nargisi Kofta", "Malai Kofta", "Shahi Tukda", "Seviyan", "Dum Aloo", "Tandoori Prawns",
      "Kachumber", "Patra", "Pesarattu", "Ragi Roti", "Pongal", "Bhel Puri", "Vegan Pulao", "Navratan Korma",
      "Cabbage Kofta Curry", "Karela Fry", "Chana Chaat", "Sooji Halwa", "Khandvi", "Vada Pav", "Methi Thepla",
      "Maharashtrian Thali", "Macher Jhol", "Mishti Doi", "Rasgulla", "Lassi", "Doi Maach", "Fish Curry",
      "Shorshe Ilish", "Macher Jhol", "Chingri Malai Curry", "Aloo Chana", "Aloo Methi", "Dhokla", "Soya Chaap",
      "Chhole", "Panchmel Dal", "Gatte Ki Sabzi", "Sannas", "Vazhapoo Poriyal", "Kadamba Saadham", "Pesarattu",
      "Methi Malai Murg", "Chana Bhatura", "Kadhi Pakora", "Malai Kofta", "Makki Ki Roti", "Sarson Da Saag", "Tandoori Roti",
      "Kadhi", "Methi Paratha", "Aloo Tikki", "Methi thepla", "Pulao", "Naan", "Dosa", "Vada", "Dhokla", "Papad",
      "Bhindi Masala", "Maharashtrian Puran Poli", "Methi Aloo", "Dosa", "Chaas", "Zafrani Pulao", "Murg Malai Kebab",

      # Chinese Dishes
      "Kung Pao Chicken", "Chow Mein", "Spring Rolls", "Sweet and Sour Chicken", "Szechuan Chicken", "Mapo Tofu",
      "Dumplings", "Peking Duck", "Dim Sum", "Hot and Sour Soup", "Egg Fried Rice", "Chop Suey", "General Tso’s Chicken",
      "Beef with Broccoli", "Wonton Soup", "Chinese Hot Pot", "Char Siu", "Zha Jiang Mian", "Cantonese Roast Duck",
      "Lemon Chicken", "Shrimp Fried Rice", "Mongolian Beef", "Chicken with Cashew Nuts", "Black Bean Sauce Chicken",
      "Chili Crab", "Fish Fragrant Eggplant", "Braised Pork Belly", "Steamed Fish with Ginger and Scallions",
      "Chinese Scallion Pancakes", "Chashu", "Chili Oil Noodles", "Dim Sum", "Xiaolongbao", "Yangzhou Fried Rice",
      "Jiaozi", "Mu Shu Pork", "Shumai", "Egg Foo Young", "Fish in Black Bean Sauce", "Sichuan Hot Pot", "Steamed Buns",
      "Chongqing Chicken", "Pineapple Fried Rice", "Sichuan Pork", "Mongolian Lamb", "Chinese BBQ Ribs", "Tonkotsu Ramen",
      "Char Kway Teow", "Ma La Xiang Guo", "Sichuan Dan Dan Noodles", "Chilled Tofu with Century Egg", "Tea-Smoked Duck",
      "Moo Shu Pork", "Beef and Black Pepper Stir Fry", "Crispy Duck", "Cantonese Steamed Fish", "Salt and Pepper Shrimp",
      "Crispy Sweet and Sour Pork", "Eggplant with Garlic Sauce", "Taiwanese Beef Noodles", "Sichuan Beef Noodles",
      "Shredded Pork with Garlic Sauce", "Sichuan Eggplant", "Red-Braised Pork", "Wok-Seared Prawns", "Steamed Pork Buns",
      "Sweet and Sour Fish", "Braised Tofu with Mushrooms", "Peking Roast Duck", "Shredded Beef with Peppers",
      "Fried Shanghai Noodles", "Tofu Stir Fry with Vegetables", "Pineapple Chicken", "Lamb with Cumin", "Hot and Sour Soup",
      "Shrimp Toast", "Wok-Fried Vegetables", "Chongqing Noodles", "Shanghai Soup Dumplings", "Baked Crab with Cheese",
      "Shredded Beef with Peppers", "Ginger Chicken", "Steamed Dumplings", "Chinese Lamb Skewers", "Shredded Pork with Cabbage",
      "Fried Wontons", "Sticky Rice with Mango", "Shrimp Dumplings", "Wonton Soup", "Baked Pork Buns", "Sichuan Style Tofu",
      "Pineapple Fried Rice", "Peking Duck Pancakes", "Chinese Hot Pot", "Mongolian Beef", "Baked Dim Sum",
      "Crispy Peking Duck", "Braised Eggplant with Pork", "Scallion Pancakes", "Sichuan Chili Noodles", "Wok-Fried Lobster",
      "Wok-Fried Prawns", "Lemon Sauce Chicken", "Beef and Choy Sum Stir Fry", "Mongolian Beef Skewers", "Tofu with Chili Sauce"

}

cooking_adjectives= [
    # Taste Descriptors
    "Sweet", "Savory", "Spicy", "Sour", "Bitter", "Umami",
    "Tangy", "Mild", "Rich", "Sweet-and-sour", "Zesty",
    "Pungent", "Earthy", "Fruity", "Citrusy", "Herbal",
    "Nutty", "Smoky", "Creamy", "Buttery", "Salty",
    "Spiced", "Delicate", "Fiery", "Sweetish", "Aromatic",
    "Syrupy", "Peppery", "Sourish", "Acidic", "Nectarous",
    "Minty", "Savory-sweet", "Caramelly", "Nutty-sweet", "Tangy-sweet",
    "Balsamic", "Vinegary", "Funky", "Sharp", "Salty-sweet",
    "Toasty", "Sappy", "Cloying", "Malty", "Savory-savory",
    "Warm", "Hot", "Chilly", "Sweet-spicy", "Nutty-salty",
    "Zingy", "Tart", "Syrupy-sweet", "Peppery-sweet", "Honeyed",
    "Caramelized", "Sweet-and-spicy", "Fruity-sweet", "Zesty-sweet", "Lemony",
    "Mellow", "Toasty", "Decadent", "Savory-sweet", "Earthy-sweet",
    "Sweet-savory", "Umami-rich", "Savory-bitter", "Syrupy-tart", "Gourmet-sweet",
    "Luscious", "Richly-flavored", "Flavor-packed", "Comfortingly-sweet", "Tangy-rich",
    "Zesty-spicy", "Floral", "Toffee-like", "Coconutty", "Spice-infused",
    "Exotic", "Lively", "Cheesy", "Nutty-spicy", "Peanutty",
    "Wholesome", "Satiating", "Rich-spicy", "Tropical", "Zesty-sour",

    # Texture Descriptors
    "Crunchy", "Crispy", "Tender", "Juicy", "Moist",
    "Chewy", "Flaky", "Silky", "Gritty", "Velvety",
    "Soft", "Firm", "Light", "Dense", "Sticky",
    "Greasy", "Crumbly", "Smooth", "Coarse", "Dry",
    "Powdery", "Spongy", "Grainy", "Fibrous", "Succulent",
    "Velvety", "Fluffy", "Creamy", "Airy", "Doughy",
    "Brittle", "Luscious", "Springy", "Rubbery", "Soggy",
    "Gooey", "Pasty", "Velvety-smooth", "Mushy", "Cohesive",
    "Rubbery", "Flaky-crisp", "Silky-smooth", "Chunky", "Lumpy",
    "Smooth-textured", "Softened", "Bouncy", "Unctuous", "Fibrous",
    "Syrupy", "Crusty", "Flaky-crisp", "Frothy", "Fudgy",
    "Gritty-smooth", "Silken", "Waxy", "Spongey", "Flaky-tender",
    "Chewy-tender", "Crusty-tender", "Soft-crunchy", "Nutty-crunchy", "Creamy-crisp",
    "Velvety-rich", "Moist-crumbly", "Firm-tender", "Smooth-dense", "Soft-flaky",
    "Rough", "Pleasantly-grainy", "Satisfyingly-crunchy", "Ethereal", "Melt-in-your-mouth",
    "Crumbly-soft", "Richly-flavored", "Nutty-crunchy", "Fluffy-tender", "Succulent-rich",

    # Cooking Method Descriptors
    "Grilled", "Roasted", "Baked", "Fried", "Sautéed",
    "Steamed", "Poached", "Blanched", "Braised",
    "Simmered", "Barbecued", "Sliced", "Chopped",
    "Minced", "Blended", "Whipped", "Toasted",
    "Caramelized", "Candied", "Pickled", "Stir-fried",
    "Microwaved", "Broiled", "Smoked", "Fermented", "Cured",
    "Roasted", "Basted", "Glazed", "Layered", "Stuffed",
    "Confit", "Sous-vide", "Brined", "Emulsified", "Dehydrated",
    "Churned", "Diced", "Simmered-down", "Skillet-cooked", "Pan-fried",
    "Marinated", "Riced", "Stuffed", "Layered", "Simmered",
    "Flambéed", "Crusted", "Coated", "Folded", "Puréed",
    "Tossed", "Reduced", "Basted", "Wok-fried", "Seasoned",
    "Boiled", "Baked-golden", "Roasted-crispy", "Smoky-grilled", "Fried-crispy",
    "Cooked-to-perfection", "Stewed", "Deep-fried", "Flash-fried", "Slow-cooked",
    "Fire-roasted", "Blitzed", "Tandoor-cooked", "Pressure-cooked", "Crisped",
    "Infused", "Marinated", "Roasted-then-baked", "Simmered-then-stirred", "Pan-seared",
    "Simmered-gently", "Stir-fried-vigorously", "Baked-until-golden", "Grilled-to-perfection", "Cooked-over-open-flame",

    # Color Descriptors
    "Golden", "Brown", "Green", "Red", "Yellow",
    "Black", "White", "Orange", "Purple", "Vibrant",
    "Pale", "Bright", "Deep", "Rustic", "Dark",
    "Faded", "Brilliant", "Pastel", "Muted", "Bold",
    "Glossy", "Shiny", "Matte", "Iridescent", "Dull",
    "Saturated", "Radiant", "Translucent", "Opaque", "Lustrous",
    "Colorful", "Hued", "Tinted", "Shimmering", "Blushing",
    "Luminous", "Striking", "Eye-catching", "Warm-hued", "Cool-toned",
    "Sunset-colored", "Brightly-hued", "Monochrome", "Dappled", "Shaded",
    "Color-rich", "Colorful", "Subdued", "Contrasting", "Highlighting",
    "Fiery", "Brightly-colored", "Vivid", "Radiant-hued", "Cheerful-colored",
    "Brilliantly-colored", "Eye-catching-hued", "Pastel-hued", "Richly-colored", "Soft-hued",
    "Glowing", "Brilliantly-bright", "Deep-hued", "Lustrous-hued", "Chromatic",
    "Saturated-color", "Color-drenched", "Delicate-hued", "Gleaming", "Vibrantly-hued",
    "Earthy-toned", "Pastel-toned", "Brilliantly-lit", "Warm-colored", "Cool-colored",

    # Miscellaneous Descriptors
    "Fresh", "Seasonal", "Homemade", "Gourmet",
    "Exotic", "Traditional", "Contemporary", "Elegant",
    "Casual", "Comforting", "Hearty", "Satisfying",
    "Simple", "Elaborate", "Balanced", "Decadent",
    "Wholesome", "Nutritious", "Artisanal", "Crafted",
    "Luscious", "Indulgent", "Innovative", "Hearty",
    "Nostalgic", "Fusion", "Luxurious", "Fragrant",
    "Colorful", "Zingy", "Tantalizing", "Irresistible",
    "Whimsical", "Satisfying", "Comforting", "Nutritious",
    "Homey", "Crafted", "Heartfelt", "Simple", "Intricate",
    "Daring", "Inspiring", "Classic", "Timeless", "Effervescent",
    "Eclectic", "Bountiful", "Gastronomic", "Sustainable", "Artful",
    "Inviting", "Bistro-style", "Rustic-chic", "Charming", "Homely",
    "Exuberant", "Radiant", "Flavorsome", "Comforting", "Alluring",
    "Elegant-yet-simple", "Flavorful", "Satiating", "Cultural", "Diverse",
    "Vibrantly-colored", "Mouthwatering", "Incredibly-tasty", "Gourmet-inspired", "Soulful",
    "Enriching", "Sublime", "Fantastical", "Epicurean", "Authentic",
    "Invitingly-prepared", "Celebratory", "Culturally-inspired", "Aesthetically-pleasing", "Visually-stunning",
    "Flavor-forward", "Finesse", "Aromatic-tasting", "Richly-expressive", "Sumptuous",
    "Enchanting", "Pleasurable", "Trendy", "Upbeat", "Savory-sweet",
    "Lush", "Vibrant", "Charming", "Bountiful", "Effervescent"
]



# Create a list of tuples for the dataset
data = []

# Add cooking processes to the dataset
for process in cooking_verbs:
    data.append({"word": process, "label": "verb", "genre": "cooking"})

# Add cooking foods to the dataset
for items in cooking_nouns:
  data.append({"word": items, "label": "noun", "genre": "cooking"})

for adj in cooking_adjectives:
  data.append({"word": adj, "label": "adjective", "genre": "cooking"})


# Create a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('cooking_dataset.csv', index=False)

print("Cooking words Dataset with words and labels created successfully!")

gaming_nouns = [
    "Gameplay", "Character", "Level", "Quest", "Strategy", "Boss", "Loot", "Weapon",
    "Map", "Mission", "Cutscene", "Multiplayer", "Achievement", "Skill", "Power-up",
    "Enemy", "Avatar", "Storyline", "Environment", "Community", "Enemy AI", "Skill tree",
    "Inventory", "Health", "Checkpoint", "Player", "Difficulty", "Crafting", "Sandbox",
    "Faction", "Guild", "Leaderboard", "Arena", "Expansion", "PVE", "PVP", "Emote",
    "Beta", "Patch", "Questline", "NPC", "Save point", "Endgame", "Clans",
    "Achievement system", "Expansions", "Skill level", "Resources", "Farming", "Trophy",
    "Perk", "Artifact", "Lore", "Game mode", "Matchmaking", "Replay", "Tutorial",
    "Crafting station", "Bounty", "Event", "Dungeon", "Raid", "Boss fight", "Narrative",
    "Season", "Bundle", "Itemization", "Map editor", "Meta-game", "Match", "Protagonist",
    "Antagonist", "Expedition", "Co-op", "Tournament", "Endurance mode", "Skill cooldown",
    "Game world", "Patch notes", "Game lore", "Progression system", "Meta",
    "Faction leader", "Side quest", "Character arc", "Game trailer", "DLC",
    "Game session", "Player stats", "Server", "Playstyle", "Gameplay loop", "Crossover",
    "Virtual reality", "Augmented reality", "Tactical shooter", "Expansion pack",
    "Heroic deed", "Combat system", "Character build", "PvE content", "PvP arena",
    "Seasonal event", "Character progression", "Voice line", "Game script", "Epic loot",
    "Guild membership", "User interface", "Skill synergy", "Resource node", "Clue",
    "Artifact set", "Patch log", "World event", "Lore drop", "Tactical advantage",
    "Playtesting", "Game environment", "Faction dynamics", "Replay mode",
    "Challenge arena", "Game assets", "Cinematic experience", "Quest chain",
    "Game mechanics", "Easter egg", "Endgame strategy", "Battlefield", "Hero abilities",
    "Content creator", "Game universe", "Role-playing", "Item slot", "Game client",
    "User feedback", "Game community", "Strategy guide", "Lore master",
    "Server migration", "Event planner", "Gameplay loop", "Challenge rating",
    "Skill challenge", "Loot table", "Game mechanic", "Progress tracker",
    "Clan system", "Game designer", "Character traits", "Quest log",
    "Player narrative", "Crafting component", "Dynamic event", "Game cycle",
    "Victory condition", "Skill set", "Narrative thread",
    "League of Legends", "Ahri", "Yasuo", "Jinx", "Thresh", "Garen", "Lux", "Zed",
    "Darius", "Katarina", "Riven", "Lee Sin", "Akali", "Ezreal", "Miss Fortune",
    "Vayne", "Jhin", "Kai'Sa", "Kassadin", "Gragas", "Orianna", "Rumble", "Teemo",
    "Nasus", "Malphite", "Morgana", "Lucian", "Rakan", "Zyra", "Sett", "Kayn",
    "Sylas", "Senna", "Aphelios", "Lillia", "Seraphine", "Gwen", "Bard", "Fiora",
    "Diana", "Irelia", "Taliyah", "Kennen", "Nautilus", "Ekko", "Kled", "Gnar",
    "Ziggs", "Janna", "Soraka", "Ashe", "Leona", "Blitzcrank", "Cho'Gath",
    "Veigar", "Karma", "Fiddlesticks", "Sion", "Vladimir", "Modes",
    "Summoner's Rift", "ARAM", "Teamfight Tactics", "Clash", "Ranked",
    "Normal Blind Pick", "Normal Draft Pick", "Custom Games", "Bot Games",
    "Rotating Game Modes", "Dota 2", "Anti-Mage", "Invoker", "Pudge",
    "Crystal Maiden", "Lina", "Earthshaker", "Terrorblade", "Riki",
    "Sniper", "Phantom Assassin", "Queen of Pain", "Zeus", "Sven",
    "Tinker", "Wraith King", "Bristleback", "Kunkka", "Lycan",
    "Timbersaw", "Warlock", "Shadow Fiend", "Axe", "Juggernaut",
    "Dazzle", "Disruptor", "Pugna", "Vengeful Spirit", "Mirana",
    "Enchantress", "Nature's Prophet", "Phantom Lancer", "Sand King",
    "Faceless Void", "Storm Spirit", "Lone Druid", "Oracle", "Monkey King",
    "Razor", "Techies", "Windranger", "Modes", "All Pick", "Captain's Mode",
    "Random Draft", "All Random", "Single Draft", "Deathmatch",
    "Ability Draft", "Turbo Mode", "Co-op vs. AI", "Custom Games",
    "Counter-Strike: Global Offensive", "Terrorists", "Counter-Terrorists",
    "Captain Price", "John \"Soap\" MacTavish", "Ghost", "Mace", "Roze",
    "Klaus", "GIGN", "SAS", "SWAT", "FBI", "Delta Force", "Modes",
    "Bomb Defusal", "Hostage Rescue", "Deathmatch", "Arms Race",
    "Demolition", "Danger Zone", "Wingman", "Custom Games", "Fortnite",
    "Jonesy", "Peely", "Lara Croft", "Spider-Man", "Drift", "Fishstick",
    "Midas", "The Mandalorian", "Chun-Li", "Ninja", "Deadpool",
    "Raven", "The Foundation", "Boba Fett", "Alleycat", "Summer Skye",
    "Renegade Raider", "Galaxy Scout", "Aerial Assault Trooper", "Modes",
    "Battle Royale", "Creative Mode", "Save the World", "Team Rumble",
    "Squad Mode", "Duos", "Solos", "Arena Mode", "Limited Time Modes",
    "Overwatch", "Tracer", "Reinhardt", "Mercy", "Genji", "D.Va",
    "Winston", "Soldier: 76", "Moira", "Zenyatta", "Orisa", "Pharah",
    "Sombra", "Echo", "Baptiste", "Ashe", "Sigma", "Brigitte", "Doomfist",
    "Reaper", "Hanzo", "Widowmaker", "Junkrat", "Roadhog", "Kiriko",
    "Sojourn", "Modes", "Quick Play", "Competitive Play", "Arcade",
    "Custom Games", "Capture the Flag", "Deathmatch", "Control",
    "Hybrid", "Escort", "Flashpoint", "Call of Duty: Warzone",
    "Ghost", "Captain Price", "Alex", "Roze", "Soap", "Mace",
    "Klaus", "Frank Woods", "Simon Ghost Riley", "David Mason",
    "Alex Mason", "Valeria Garza", "General Shepherd", "Seraph",
    "Modes", "Battle Royale", "Plunder", "Resurgence", "Mini Royale",
    "Payload", "DMZ", "Valorant", "Jett", "Sage", "Cypher", "Phoenix",
    "Raze", "Breach", "Sova", "Killjoy", "Skye", "Chamber", "Viper",
    "Killjoy", "Omen", "Brimstone", "Neon", "Fade", "Modes",
    "Unrated", "Spike Rush", "Competitive", "Deathmatch", "Escalation",
    "Spike Planting", "Custom Games", "Apex Legends", "Wraith",
    "Bloodhound", "Gibraltar", "Lifeline", "Pathfinder", "Octane",
    "Horizon", "Valkyrie", "Fuse", "Seer", "Newcastle", "Caustic",
    "Mirage", "Bangalore", "Ash", "Revenant", "Loba", "Rampart",
    "Mad Maggie", "Krypto", "Gibraltar", "Modes", "Battle Royale",
    "Ranked", "Arena", "Training", "Firing Range", "Super Smash Bros. Ultimate",
    "Mario", "Link", "Pikachu", "Samus", "Kirby", "Zelda", "Donkey Kong",
    "Fox", "Marth", "Luigi", "Sonic", "Pac-Man", "Bayonetta",
    "Joker", "Cloud Strife", "Sephiroth", "Duck Hunt", "Wario",
    "Toon Link", "Richter", "Simon", "Ike", "Villager", "Isabelle",
    "Game & Watch", "Mega Man", "Greninja", "Inkling", "Modes",
    "Smash", "Time Attack", "Classic Mode", "Adventure Mode",
    "Squad Strike", "Tourney Mode", "All-Star Mode", "Training Mode",
    "Minecraft", "Steve", "Alex", "Creeper", "Enderman", "Zombie",
    "Skeleton", "Herobrine", "Panda", "Witch", "Shulker", "Villager",
    "Phantom", "Wither", "Ender Dragon", "Illager", "Evoker",
    "Vindicators", "Piglin", "Strider", "Drowned", "Axolotl",
    "Modes", "Survival Mode", "Creative Mode", "Adventure Mode",
    "Spectator Mode", "Hardcore Mode", "Minecraft Dungeons",
    "Warrior", "Mage", "Archer", "Rogue", "Enchantress", "Necromancer",
    "Modes", "Adventure Mode", "Local Co-op", "Online Co-op", "Seasons",
    "Trials", "Loot Runs", "Tower of Trials", "FIFA",
    "Lionel Messi", "Cristiano Ronaldo", "Neymar", "Kylian Mbappé",
    "Kevin De Bruyne", "Virgil van Dijk", "Mohamed Salah", "Harry Kane",
    "Karim Benzema", "Sadio Mané", "Gareth Bale", "Robert Lewandowski",
    "Kaká", "Ronaldinho", "David Beckham", "Thierry Henry",
    "Zinedine Zidane", "Ronaldinho", "Rivaldo", "Pele", "Modes",
    "Career Mode", "Ultimate Team", "Pro Clubs", "VOLTA Football",
    "Skill Games", "Season Mode", "Tournaments", "Rocket League",
    "Octane", "Dominus", "Batmobile", "McLaren", "Fennec", "Nimbus",
    "Jager", "Takumi", "Venom", "Breakout", "Sentinel", "Chakra",
    "Ripper", "Mantis", "Modes", "Soccar", "Hoops", "Rumble",
    "Dropshot", "Battle Cars", "Custom Games", "Street Fighter V",
    "Ryu", "Chun-Li", "M. Bison", "Akuma", "Ken", "Guile",
    "Blanka", "Cammy", "Zangief", "Karin", "Sakura", "Juri",
    "Laura", "Menat", "Kage", "Dan Hibiki", "G", "Rashid",
    "Falke", "Colleen", "Modes", "Versus Mode", "Arcade Mode",
    "Story Mode", "Training Mode", "Online Matches", "Survival Mode",
    "World of Warcraft", "Human Paladin", "Night Elf Druid",
    "Orc Warrior", "Undead Mage", "Tauren Shaman", "Blood Elf Hunter",
    "Dwarf Rogue", "Gnome Warlock", "Pandaren Monk", "Demon Hunter",
    "Nightborne Mage", "Void Elf", "Zandalari Troll", "Death Knight",
    "Warlock", "Rogue", "Priest", "Hunter", "Mage", "Warrior",
    "Paladin", "Druid", "Monk", "Modes", "PvE Raids", "Mythic+ Dungeons",
    "PvP Arenas", "Battlegrounds", "World Quests", "Story Quests",
    "Timewalking", "Island Expeditions", "Genshin Impact", "Aether",
    "Amber", "Diluc", "Zhongli", "Klee", "Fischl", "Venti", "Xiangling",
    "Ganyu", "Hu Tao", "Yae Miko", "Bennett", "Raiden Shogun",
    "Mona", "Keqing", "Xingqiu", "Albedo", "Kazuha", "Yoimiya",
    "Tartaglia", "Scaramouche", "Shinobu", "Kuki Shinobu", "Cyno",
    "Nilou", "Lumine", "Kaeya", "Sucrose", "Lisa", "Beidou",
    "Xiao", "Modes", "Open World Exploration", "Co-op Mode",
    "Domains", "Spiral Abyss", "Events", "Story Quests",
    "Archon Quests", "Daily Commissions", "World Events",
    "Monster Hunter: World", "Hunter", "Zorah Magdaros", "Nergigante",
    "Rathalos", "Agnaktor", "Kushala Daora", "Elder Dragon",
    "Safi'jiiva", "Arch Tempered", "Barioth", "Brachydios",
    "Diablos", "Khezu", "Xeno'jiiva", "Teostra", "Velkhana",
    "Rajang", "Modes", "Hunt", "Expeditions", "Events",
    "Guiding Lands", "Quest Boards", "Monster Hunts", "Arena Quests",
    "World of Tanks", "T-34", "Panzer IV", "Sherman", "KV-1",
    "M4A2", "Heavy Tank", "Medium Tank", "Light Tank", "Artillery",
    "Premium Tanks", "Tigers", "IS-7", "Jagdtiger", "Churchill",
    "E-100", "Maus", "Modes", "Standard Battles", "Ranked Battles",
    "Special Operations", "Training", "Global Map", "Clan Wars",
    "World of Tanks Console", "Fall Guys: Ultimate Knockout",
    "Fall Guy", "Skelly", "Glorious Jelly", "Fruity", "Frog",
    "Cat", "Dog", "T-Rex", "Golden Egg", "Superhero", "Dino",
    "Modes", "Squad Mode", "Solo Show", "Duos Show", "LTM Events",
    "Custom Games", "Seasonal Events", "Among Us", "Crewmate",
    "Imposter", "Engineer", "Guardian Angel", "Shapeshifter",
    "Tasks", "Maps", "Classic Mode", "Modes", "Classic",
    "Hide and Seek", "Short Tasks", "Long Tasks", "Quick Chat",
    "League of Legends",
    "Ahri", "Yasuo", "Jinx", "Thresh", "Garen", "Lux", "Zed", "Darius", "Katarina",
    "Riven", "Lee Sin", "Akali", "Ezreal", "Miss Fortune", "Vayne", "Jhin", "Kai'Sa",
    "Kassadin", "Gragas", "Orianna", "Rumble", "Teemo", "Nasus", "Malphite", "Morgana",
    "Lucian", "Rakan", "Zyra", "Sett", "Kayn", "Sylas", "Senna", "Aphelios", "Lillia",
    "Seraphine", "Gwen", "Bard", "Fiora", "Diana", "Irelia", "Taliyah", "Kennen",
    "Nautilus", "Ekko", "Kled", "Gnar", "Ziggs", "Janna", "Soraka", "Ashe", "Leona",
    "Blitzcrank", "Cho'Gath", "Veigar", "Karma", "Fiddlesticks", "Sion", "Vladimir",
    "Modes", "Summoner's Rift", "ARAM", "Teamfight Tactics", "Clash", "Ranked",
    "Normal Blind Pick", "Normal Draft Pick", "Custom Games", "Bot Games", "Rotating Game Modes",
    "Dota 2",
    "Anti-Mage", "Invoker", "Pudge", "Crystal Maiden", "Lina", "Earthshaker", "Terrorblade",
    "Riki", "Sniper", "Phantom Assassin", "Queen of Pain", "Zeus", "Sven", "Tinker",
    "Wraith King", "Bristleback", "Kunkka", "Lycan", "Timbersaw", "Warlock", "Shadow Fiend",
    "Axe", "Juggernaut", "Dazzle", "Disruptor", "Pugna", "Vengeful Spirit", "Mirana",
    "Enchantress", "Nature's Prophet", "Phantom Lancer", "Sand King", "Faceless Void",
    "Storm Spirit", "Lone Druid", "Oracle", "Monkey King", "Razor", "Techies", "Windranger",
    "Modes", "All Pick", "Captain's Mode", "Random Draft", "All Random", "Single Draft",
    "Deathmatch", "Ability Draft", "Turbo Mode", "Co-op vs. AI", "Custom Games",
    "Counter-Strike: Global Offensive",
    "Terrorists", "Counter-Terrorists", "Captain Price", "John \"Soap\" MacTavish",
    "Ghost", "Mace", "Roze", "Klaus", "GIGN", "SAS", "SWAT", "FBI", "Delta Force",
    "Modes", "Bomb Defusal", "Hostage Rescue", "Deathmatch", "Arms Race", "Demolition",
    "Danger Zone", "Wingman", "Custom Games", "Fortnite",
    "Jonesy", "Peely", "Lara Croft", "Spider-Man", "Drift", "Fishstick", "Midas",
    "The Mandalorian", "Chun-Li", "Ninja", "Deadpool", "Raven", "The Foundation",
    "Boba Fett", "Alleycat", "Summer Skye", "Renegade Raider", "Galaxy Scout", "Aerial Assault Trooper",
    "Modes", "Battle Royale", "Creative Mode", "Save the World", "Team Rumble",
    "Squad Mode", "Duos", "Solos", "Arena Mode", "Limited Time Modes", "Overwatch",
    "Tracer", "Reinhardt", "Mercy", "Genji", "D.Va", "Winston", "Soldier: 76",
    "Moira", "Zenyatta", "Orisa", "Pharah", "Sombra", "Echo", "Baptiste", "Ashe",
    "Sigma", "Brigitte", "Doomfist", "Reaper", "Hanzo", "Widowmaker", "Junkrat",
    "Roadhog", "Kiriko", "Sojourn",
    "Modes", "Quick Play", "Competitive Play", "Arcade", "Custom Games", "Capture the Flag",
    "Deathmatch", "Control", "Hybrid", "Escort", "Flashpoint", "Call of Duty: Warzone",
    "Ghost", "Captain Price", "Alex", "Roze", "Soap", "Mace", "Klaus", "Frank Woods",
    "Simon Ghost Riley", "David Mason", "Alex Mason", "Valeria Garza", "General Shepherd",
    "Seraph", "Operator", "Modes", "Battle Royale", "Plunder", "Resurgence", "Mini Royale",
    "Payload", "DMZ", "Valorant",
    "Jett", "Sage", "Cypher", "Phoenix", "Raze", "Breach", "Sova", "Killjoy",
    "Skye", "Chamber", "Viper", "Killjoy", "Omen", "Brimstone", "Neon", "Fade",
    "Modes", "Unrated", "Spike Rush", "Competitive", "Deathmatch", "Escalation",
    "Spike Planting", "Custom Games", "Apex Legends",
    "Wraith", "Bloodhound", "Gibraltar", "Lifeline", "Pathfinder", "Octane", "Horizon",
    "Valkyrie", "Fuse", "Seer", "Newcastle", "Caustic", "Mirage", "Bangalore",
    "Ash", "Revenant", "Loba", "Rampart", "Mad Maggie", "Krypto",
    "Modes", "Battle Royale", "Ranked", "Arena", "Training", "Firing Range",
    "Super Smash Bros. Ultimate",
    "Mario", "Link", "Pikachu", "Samus", "Kirby", "Zelda", "Donkey Kong", "Fox",
    "Marth", "Luigi", "Sonic", "Pac-Man", "Bayonetta", "Joker", "Cloud Strife",
    "Sephiroth", "Duck Hunt", "Wario", "Toon Link", "Richter", "Simon", "Ike",
    "Villager", "Isabelle", "Game & Watch", "Mega Man", "Greninja", "Inkling",
    "Modes", "Smash", "Time Attack", "Classic Mode", "Adventure Mode", "Squad Strike",
    "Tourney Mode", "All-Star Mode", "Training Mode", "Minecraft",
    "Steve", "Alex", "Creeper", "Enderman", "Zombie", "Skeleton", "Herobrine",
    "Panda", "Witch", "Shulker", "Villager", "Phantom", "Wither", "Ender Dragon",
    "Illager", "Evoker", "Vindicators", "Piglin", "Strider", "Drowned", "Axolotl",
    "Modes", "Survival Mode", "Creative Mode", "Adventure Mode", "Spectator Mode",
    "Hardcore Mode", "Minecraft Dungeons",
    "Warrior", "Mage", "Archer", "Rogue", "Enchantress", "Necromancer",
    "Modes", "Adventure Mode", "Local Co-op", "Online Co-op", "Seasons",
    "Trials", "Loot Runs", "Tower of Trials",
    "FIFA",
    "Lionel Messi", "Cristiano Ronaldo", "Neymar", "Kylian Mbappé", "Kevin De Bruyne",
    "Virgil van Dijk", "Mohamed Salah", "Harry Kane", "Karim Benzema", "Sadio Mané",
    "Gareth Bale", "Robert Lewandowski", "Kaká", "Ronaldinho", "David Beckham",
    "Thierry Henry", "Zinedine Zidane", "Rivaldo", "Pele",
    "Modes", "Career Mode", "Ultimate Team", "Pro Clubs", "VOLTA Football",
    "Skill Games", "Season Mode", "Tournaments",
    "Rocket League",
    "Octane", "Dominus", "Batmobile", "McLaren", "Fennec", "Nimbus", "Jager",
    "Takumi", "Venom", "Breakout", "Sentinel", "Chakra", "Ripper", "Mantis",
    "Modes", "Soccar", "Hoops", "Rumble", "Dropshot", "Battle Cars", "Custom Games",
    "Street Fighter V",
    "Ryu", "Chun-Li", "M. Bison", "Akuma", "Ken", "Guile", "Blanka", "Cammy",
    "Zangief", "Karin", "Juri", "Laura", "Menat", "Kage", "Sakura",
    "Dan Hibiki", "G", "Dhalsim", "Colleen", "Vega",
    "Modes", "Arcade Mode", "Survival Mode", "Story Mode", "Training Mode",
    "Versus Mode", "Online Matchmaking"
    ]

gaming_verbs = [
    "Attack", "Defend", "Collect", "Explore", "Level up", "Craft", "Equip", "Battle",
    "Join", "Complete", "Upgrade", "Heal", "Spawn", "Steal", "Achieve", "Dodge",
    "Interact", "Challenge", "Stealth", "Respawn", "Loot", "Craft", "Summon",
    "Engage", "Capture", "Assassinate", "Train", "Discover", "Navigate", "Race",
    "Trade", "Modify", "Dominate", "Conquer", "Steer", "Negotiate", "Cooperate",
    "Challenge", "Escape", "Revitalize", "Evaluate", "Execute", "Retain",
    "Communicate", "Finesse", "Alter", "Optimize", "Advance", "Synthesize",
    "Narrate", "Deploy", "Analyze", "Present", "Explore", "Incorporate",
    "Capture", "Engage", "Sculpt", "Refocus", "Disrupt", "Leverage",
    "Facilitate", "Adapt", "Transform", "Consolidate", "Conquer", "Expand",
    "Innovate", "Refine", "Restructure", "Enhance", "Revise", "Utilize",
    "Generate", "Pioneer", "Coordinate", "Guide", "Execute", "Emphasize",
    "Curate", "Synthesize", "Mobilize", "Innovate", "Clarify", "Demonstrate",
    "Infiltrate", "Navigate", "Rebalance", "Collaborate", "Elevate", "Motivate",
    "Empathize", "Extrapolate", "Engender", "Facilitate", "Integrate", "Stimulate",
    "Orchestrate"
]

gaming_adjectives = [
    "Epic", "Legendary", "Rare", "Powerful", "Challenging", "Dynamic", "Open-world",
    "Intense", "Strategic", "Fast-paced", "Immersive", "Vibrant", "Complex",
    "Realistic", "Futuristic", "Customizable", "Addictive", "Multiplayer",
    "Engaging", "In-game", "Charming", "Nostalgic", "Grim", "Sleek", "Colorful",
    "Mysterious", "Challenging", "Open-ended", "User-friendly", "Visceral",
    "Unique", "Atmospheric", "Stylized", "Puzzling", "Interactive", "Engrossing",
    "Multifaceted", "Satisfying", "Intuitive", "Cinematic", "Retro", "Innovative",
    "Groundbreaking", "Compelling", "Intense", "Frantic", "Subtle", "Whimsical",
    "Captivating", "Diverse", "Visceral", "Cohesive", "Evolving", "Futuristic",
    "Lush", "Aesthetic", "Engrossing", "Spectacular", "Strategic", "Intrepid",
    "Daring", "Intriguing", "Visceral", "Tactical", "Immersive", "Captivating",
    "Harrowing", "Fast-paced", "Engaging", "Robust", "Polished", "High-stakes",
    "Experimental", "Daring", "Memorable", "Intense", "Epic", "Visually stunning",
    "Thought-provoking", "Rewarding", "Charming", "Intellectual", "Interactive",
    "Visually captivating", "Adrenaline-fueled", "Masterful", "Vibrant", "Captivating",
    "Dynamic", "Imaginative", "Intriguing", "Robust", "Nostalgic", "Sophisticated",
    "Fluid", "Resilient", "Electrifying", "Empowering", "Gripping", "Challenging",
    "Authentic", "Epic", "Thrilling", "Compelling", "Strategic", "Engaging",
    "Dynamic", "Challenging", "Intriguing", "Alluring", "Authentic", "Innovative",
    "Immersive", "Robust", "Visually striking", "Satisfying", "Layered",
    "Gripping", "Sophisticated", "Adventurous", "Fluid"
]



# Create a list of tuples for the dataset
data = []

# Add cooking processes to the dataset
for process in gaming_verbs:
    data.append({"word": process, "label": "verb", "genre": "gaming"})

# Add cooking foods to the dataset
for items in gaming_nouns:
  data.append({"word": items, "label": "noun","genre": "gaming"})

for adj in gaming_adjectives:
  data.append({"word": adj, "label": "adjective","genre": "gaming"})


# Create a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('gaming_dataset.csv', index=False)

print("Gaming words Dataset with words and labels created successfully!")

lifestyle_nouns = [
    "Routine", "Wellness", "Fitness", "Recipe", "Travel", "Mindfulness", "Lifestyle",
    "Self-care", "Diet", "Habit", "Home", "Style", "Adventure", "Health", "Balance",
    "Inspiration", "Motivation", "Vlog", "Beauty", "Mindset", "Productivity",
    "Nutrition", "Sustainability", "Hobby", "Organization", "Detox", "Goal",
    "Journal", "Environment", "Meditation", "Journey", "Decor", "Fashion",
    "Relaxation", "Community", "Retreat", "Skincare", "Experience", "Travelogue",
    "Perspective", "Self-reflection", "Motivational speaker", "Healthy lifestyle",
    "Personal journey", "Vision board", "Creative outlet", "Life coach",
    "Health challenge", "Food diary", "Fitness community", "Social network",
    "Culinary experience", "Daily habits", "Mindful eating", "Living space",
    "Inspirational story", "Digital detox", "Healthy swap", "Morning mantra",
    "Resilience", "Routine overhaul", "Happiness project", "Gratitude",
    "Self-love", "Community service", "Positive mindset", "Travel diary",
    "Art therapy", "Wellness retreat", "Cooking class", "Yoga session",
    "Fitness plan", "Meal planning", "Nutrition guide", "Hiking trail",
    "Cooking tips", "Relaxation space", "Health benefits", "Lifestyle shift",
    "Personal values", "Coping strategies", "Social gathering", "Mindful habits",
    "Creative process", "Outdoor space", "Healthy choices", "Motivational quote",
    "Mindfulness techniques", "Stress relief", "Journaling practice",
    "Well-being", "Fitness tracker", "Culinary skills", "Home sanctuary",
    "Lifestyle blog", "Mindset shift", "Social activities", "Life experiences",
    "Health workshop", "Virtual summit", "Family time", "Local events",
    "Volunteer work", "Cultural immersion", "Inspirational leaders", "Visioning",
    "Lifestyle design", "Self-care routine", "Digital content", "Wellness tips",
    "Creative outlet", "Hobby group", "Self-help resources", "Motivational content",
    "Mindfulness journey", "Healthy community", "Positive affirmations",
    "Empowerment group", "Travel experiences", "Health awareness", "Culinary traditions",
    "Self-reflection prompts", "Daily affirmations", "Life lessons", "Health innovations",
    "Personal insights", "Inspiring stories", "Positive experiences", "Personal challenges",
    "Wellness philosophies", "Lifestyle strategies", "Mindful practices",
    "Nutritional education", "Health insights", "Self-discovery tools",
    "Motivational podcasts", "Health inspirations", "Fitness journeys",
    "Wellness blogs", "Positive habits", "Inspirational journeys", "Daily rituals",
    "Cooking techniques", "Healthy eating habits", "Mindful movement",
    "Creative projects", "Personal growth", "Fitness challenges", "Life coaching",
    "Nutritional supplements", "Healthy lifestyle choices", "Meditation practices",
    "Social connections", "Lifestyle challenges", "Holistic health", "Time management",
    "Cultural diversity", "Personal reflections", "Nature therapy", "Inspirational resources",
    # New additions
    "Dietary habits", "Eco-friendly lifestyle", "Self-improvement", "Community engagement",
    "Inner peace", "Life balance", "Stress management", "Motivational speeches", "Lifestyle influencer",
    "Wellness blog", "Healthy routines", "Online community", "Learning journey", "Self-motivation",
    "Personal brand", "Life hack", "Natural living", "Outdoor adventure", "Personal development",
    "Fitness goals", "Mental health", "Urban living", "Mindful living", "Self-awareness",
    "Wellness strategy", "Healthy cooking", "Productive habits", "Routine improvement",
    "Inspiration board", "Lifestyle adjustments", "Wellness strategies", "Daily wellness",
    "Life planner", "Meal kit", "Nutritional plan", "Healthy lifestyle goals", "Self-improvement journal",
    "Family wellness", "Mental well-being", "Weekend getaway", "Outdoor exploration",
    "Digital lifestyle", "Wellness planner", "Life experiences blog", "Routine tracker",
    "Wellness insights", "Fitness app", "Outdoor adventure blog", "Health transformation",
    "Positive lifestyle", "Social wellness", "Body positivity", "Mental wellness",
    "Personal planner", "Lifestyle habits", "Wellness routine", "Travel vlogs", "Daily mindfulness"
]

lifestyle_verbs = [
    "Explore", "Create", "Cook", "Inspire", "Travel", "Organize", "Exercise",
    "Unwind", "Share", "Document", "Motivate", "Meditate", "Plan", "Transform",
    "Discover", "Simplify", "Engage", "Balance", "Connect", "Reflect",
    "Declutter", "Nurture", "Enjoy", "Cultivate", "Revitalize", "Achieve",
    "Commit", "Express", "Embrace", "Journey", "Collaborate", "Encourage",
    "Practice", "Rejuvenate", "Manifest", "Focus", "Learn", "Adapt",
    "Revitalize", "Embrace", "Experiment", "Dare", "Engage",
    "Streamline", "Nurture", "Optimize", "Illuminate", "Reassess",
    "Transform", "Celebrate", "Inspire", "Motivate", "Empower",
    "Revamp", "Cultivate", "Achieve", "Dream", "Foster", "Navigate",
    "Connect", "Share", "Engage", "Support", "Explore", "Document",
    "Experiment", "Facilitate", "Ignite", "Revive", "Challenge",
    "Clarify", "Educate", "Adapt", "Manifest", "Foster",
    "Reinvigorate", "Reflect", "Explore", "Celebrate", "Commit",
    "Navigate", "Build", "Enhance", "Transform", "Share",
    "Participate", "Advocate", "Motivate", "Empower", "Encourage",
    "Sustain", "Rejuvenate", "Articulate", "Lead", "Support",
    "Create", "Express", "Strengthen", "Evolve", "Guide",
    "Investigate", "Cultivate", "Reassess", "Design", "Innovate",
    "Plan", "Execute", "Develop", "Convene", "Integrate",
    "Refine", "Advance", "Facilitate", "Illuminate", "Harness",
    "Reorganize", "Engender", "Encourage", "Support", "Revamp",
    "Challenge", "Adapt", "Motivate", "Reflect", "Embrace",
    "Advance", "Inspire", "Initiate", "Pursue", "Explore",
    # New additions
    "Prepare", "Motivate", "Expand", "Innovate", "Balance", "Sustain",
    "Guide", "Support", "Educate", "Initiate", "Challenge", "Cooperate",
    "Strategize", "Engage", "Endure", "Adapt", "Expand", "Resolve", "Stimulate",
    "Celebrate", "Plan", "Achieve", "Motivate", "Contribute", "Empower",
    "Inspire", "Focus", "Implement", "Optimize", "Persevere", "Advance",
    "Fulfill", "Revitalize", "Perceive", "Cherish", "Organize", "Promote",
    "Innovate", "Balance", "Streamline", "Educate", "Enhance", "Develop",
    "Build", "Share", "Navigate", "Illuminate", "Pioneer", "Document",
    "Track", "Evolve", "Design", "Manage", "Direct", "Overcome", "Inspire",
    "Adapt", "Facilitate", "Connect", "Engage", "Renew", "Practice",
    "Venture", "Educate", "Reassess", "Cultivate", "Improve", "Sustain",
    "Launch", "Motivate", "Embrace", "Facilitate", "Inspire", "Adapt",
    "Integrate", "Encourage", "Guide", "Streamline", "Empower", "Transform",
    "Build", "Cultivate", "Contribute", "Revive", "Manage", "Enhance"
]

lifestyle_adjectives = [
    "Healthy", "Balanced", "Mindful", "Sustainable", "Creative", "Inspirational", "Modern"
    "Refreshing", "Organized", "Motivating", "Joyful", "Simple", "Inviting",
    "Adventurous", "Vibrant", "Holistic", "Empowering", "Authentic", "Energetic",
    "Grounded", "Stylish", "Flexible", "Innovative", "Serene", "Versatile",
    "Uplifting", "Engaging", "Nurturing", "Graceful", "Comfortable", "Productive",
    "Motivational", "Harmonious", "Radiant", "Inspiring", "Dynamic", "Enriching",
    "Rejuvenating", "Thriving", "Eco-friendly", "Balanced", "Revitalizing",
    "Motivational", "Peaceful", "Practical", "Mindful", "Stylish", "Vibrant",
    "Engaging", "Expressive", "Uplifting", "Warm", "Sociable", "Meaningful",
    "Vigorous", "Lively", "Active", "Nurturing", "Tranquil", "Optimistic",
    "Energetic", "Holistic", "Fulfilling", "Balanced", "Bright", "Inspiring",
    "Inviting", "Calm", "Sustainable", "Cozy", "Adventurous", "Active",
    "Harmonious", "Versatile", "Empowering", "Graceful", "Enriching",
    "Simple", "Serene", "Dynamic", "Motivating", "Refreshing", "Stylish",
    "Mindful", "Flexible", "Creative", "Authentic", "Peaceful", "Radiant",
    "Positive", "Comfortable", "Practical", "Innovative", "Joyful", "Grounded",
    "Thriving", "Comforting", "Holistic", "Uplifting", "Rejuvenating", "Versatile",
    "Invigorating", "Tranquil", "Soothing", "Relaxing", "Elegant", "Inspirational",
    "Energetic", "Bright", "Sustainable", "Motivational", "Exciting",
    "Calming", "Engaging", "Comfortable", "Harmonious", "Refreshing",
    "Lively", "Genuine", "Inspiring", "Warm", "Balanced", "Encouraging",
    "Motivating", "Dynamic", "Supportive", "Radiant", "Soothing", "Expressive",
    # New additions
    "Vibrant", "Efficient", "Calming", "Inviting", "Sophisticated", "Nurturing",
    "Relaxing", "Productive", "Resourceful", "Balanced", "Adventurous",
    "Mindful", "Innovative", "Dynamic", "Creative" ]

# Create a list of tuples for the dataset
data = []

# Add cooking processes to the dataset
for process in lifestyle_verbs:
    data.append({"word": process, "label": "verb","genre": "lifestyle"})

# Add cooking foods to the dataset
for items in lifestyle_nouns:
  data.append({"word": items, "label": "noun", "genre": "lifestyle"})

for adj in lifestyle_adjectives:
  data.append({"word": adj, "label": "adjective","genre": "lifestyle"})


# Create a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('lifestyle_dataset.csv', index=False)

print("Lifestyle words Dataset with words and labels created successfully!")

import pandas as pd

# Load the three datasets
lifestyle_df = pd.read_csv('lifestyle_dataset.csv')
gaming_df = pd.read_csv('gaming_dataset.csv')
cooking_df = pd.read_csv('cooking_dataset.csv')

# Combine all three datasets into one
combined_df = pd.concat([lifestyle_df, gaming_df, cooking_df], ignore_index=True)

# Save the combined DataFrame to a new CSV file
combined_df.to_csv('combined_dataset.csv', index=False)

print("Combined dataset created successfully!")

!pip install tensorflow

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Embedding, Flatten, Concatenate, GlobalAveragePooling1D, Dropout, BatchNormalization
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam

# Prepare input features and labels
X_words = combined_df['word'].values
X_labels = combined_df['label'].values
y = combined_df['genre'].values

# Step 2: Encode labels and target variable
# Encode 'label' and 'genre' as integers
label_encoder = LabelEncoder()
X_labels_encoded = label_encoder.fit_transform(X_labels)

genre_encoder = LabelEncoder()
y_encoded = genre_encoder.fit_transform(y)
y_categorical = to_categorical(y_encoded)

# Tokenize and pad 'word' input
word_tokenizer = Tokenizer()
word_tokenizer.fit_on_texts(X_words)
X_words_seq = word_tokenizer.texts_to_sequences(X_words)
X_words_padded = pad_sequences(X_words_seq, maxlen=10)

# Step 3: Neural Network Architecture
# Define input layers
word_input = Input(shape=(10,))
label_input = Input(shape=(1,))

# Embedding for word input
word_embedding = Embedding(input_dim=len(word_tokenizer.word_index) + 1, output_dim=128)(word_input)
word_embedding = Flatten()(word_embedding)

# Embedding for label input
label_embedding = Embedding(input_dim=len(label_encoder.classes_), output_dim=10)(label_input)
label_embedding = Flatten()(label_embedding)

# Combine the embeddings
combined = Concatenate()([word_embedding, label_embedding])

# # Neural network layers
dense_layer = Dense(128, activation='relu')(combined)
dense_layer = Dropout(0.5)(dense_layer)
dense_layer = Dropout(0.5)(dense_layer)
dense_layer = Dropout(0.5)(dense_layer)
dense_layer = Dropout(0.5)(dense_layer)
dense_layer = Dropout(0.5)(dense_layer)
dense_layer = Dropout(0.5)(dense_layer)

dense_layer = Dense(128, activation='relu')(combined)


output_layer = Dense(len(genre_encoder.classes_), activation='softmax')(dense_layer)

# Build and compile model
optimizer = Adam(learning_rate=0.01)
model = Model(inputs=[word_input, label_input], outputs=output_layer)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Step 4: Prepare training and testing data
X_train_words, X_test_words, X_train_labels, X_test_labels, y_train, y_test = train_test_split(
    X_words_padded, X_labels_encoded, y_categorical, test_size=0.25, random_state=42
)

# Train the model
model.fit([X_train_words, X_train_labels], y_train, epochs=35, batch_size=40, validation_split=0.2)

# Evaluate the model
accuracy = model.evaluate([X_test_words, X_test_labels], y_test)[1]
print(f"Model Accuracy: {accuracy:.2f}")

def predict_genre(word, label):
    # Preprocess the input
    word_seq = word_tokenizer.texts_to_sequences([word])
    word_padded = pad_sequences(word_seq, maxlen=10)

    # Encode the label
    label_encoded = label_encoder.transform([label])  # Use transform instead of fit_transform

    # Make the prediction
    prediction = model.predict([word_padded, np.array([label_encoded])])

    # Get the predicted genre index
    predicted_index = np.argmax(prediction)

    # Decode the predicted genre back to its original label
    predicted_genre = genre_encoder.inverse_transform([predicted_index])[0]

    return predicted_genre

import nltk
from nltk import pos_tag
from nltk.tokenize import word_tokenize

# Make sure to download the required NLTK data files if you haven't already
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
  # Example list of words

# Function to identify the part of speech for each word
def identify_pos(words):
    # Tokenize the words
    tokens = word_tokenize(' '.join(words))
    # Get the POS tags
    pos_tags = pos_tag(tokens)
    # Store the tags in a new array
    labels = [pos for word, pos in pos_tags]
    return pos_tags, labels

pos_results, pos_labels = identify_pos(top_words)

pos_tags = {
    'CC': 'conjunction',
    'CD': 'Cardinal number',
    'DT': 'Determiner',
    'EX': 'Existential there',
    'FW': 'Foreign word',
    'IN': 'Preposition',
    'JJ': 'adjective',
    'JJR': 'adjective',
    'JJS': 'adjective',
    'LS': 'List item marker',
    'MD': 'verb',
    'NN': 'noun',
    'NNS': 'noun',
    'NNP': 'noun',
    'NNPS': 'noun',
    'PDT': 'Predeterminer',
    'POS': '',
    'PRP': 'pronoun',
    'PRP$': 'pronoun',
    'RB': 'adverb',
    'RBR': 'adverb',
    'RBS': 'adverb',
    'RP': 'Particle',
    'TO': 'preposition',
    'UH': 'Interjection',
    'VB': 'verb,',
    'VBD': 'verb',
    'VBG': 'verb',
    'VBN': 'verb',
    'VBP': 'verb',
    'VBZ': 'verb',
    'WDT': 'determiner',
    'WP': 'pronoun',
    'WP$': 'pronoun',
    'WRB': 'adverb'
}

new_label=[]
for lab in pos_labels:
  if lab in pos_tags:
    new_label.append(pos_tags[lab])

print(new_label)

pre_gen = []
valid_pos=['noun', 'verb', 'adjective']

l = len(top_words)
for i in range(l):
    input_word = top_words[i]
    label = new_label[i]
    if label in valid_pos:
      predicted_genre = predict_genre(input_word, label)
      pre_gen.append(predicted_genre)


print(pre_gen)

from collections import Counter
word_counts = Counter(pre_gen)

# Calculate total number of words
total_words = len(pre_gen)

# Calculate probabilities
probabilities = {word: count / total_words for word, count in word_counts.items()}

# Print the probabilities
for word, probability in probabilities.items():
    print(word+":", probability)

from collections import Counter

# Assuming pre_gen is already defined
word_counts = Counter(pre_gen)

# Calculate total number of words
total_words = len(pre_gen)

# Create a dictionary of words with their probabilities
probabilities = {word: count / total_words for word, count in word_counts.items()}

# Find the word with maximum probability
max_word = max(probabilities, key=probabilities.get)
max_probability = probabilities[max_word]

video_genre=max_word

"""Output Text"""

print(video_genre)